### ISSUE TITLE
Uncaught TypeError: shell.openExternal is not a function

### ISSUE THREAD

**Issue by bmoren** [bmoren/p5js-snippets#20]
When opening the Reference from the menu, this error happens, need to find a different way to open the URL

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [p5js-snippets](https://github.com/bmoren/p5js-snippets) package 0.4.5

### Stack Trace

Uncaught TypeError: shell.openExternal is not a function

```
At /Users/bmoren/.atom/packages/p5js-snippets/lib/p5js-snippets.js:107

TypeError: shell.openExternal is not a function
    at Object.ref (/packages/p5js-snippets/lib/p5js-snippets.js:107:11)
    at HTMLElement.p5jsSnippetsRef (/packages/p5js-snippets/lib/p5js-snippets.js:31:39)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:352215)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350690)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:786866)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:794837)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:09.1.0 p5js-snippets:ref (div.panels-item)
```

### Non-Core Packages

```
p5js-snippets 0.4.5 
```

**Comment by bmoren** [comment]
this is also an issue for the right click open in reference menu function

**Comment by bmoren** [comment]
oddly, the more.... in the modal works so, have a look at that as well to compare
