### ISSUE TITLE
Uncaught TypeError: Error processing argument at index 0, conversion failure from false

### ISSUE THREAD

**Issue by Mycroft1891** [bmoren/p5js-snippets#9]
I have the browser-plus package installed and the command to open it is the same that this package uses for it's source fetch:

{
  "atom-workspace": {
    "ctrl-alt-o": "sourcefetch:fetch"
  }
}

Maybe the command can be changed so that it doesn't interfer.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [p5js-snippets](https://github.com/bmoren/p5js-snippets) package 0.3.1

### Stack Trace

Uncaught TypeError: Error processing argument at index 0, conversion failure from false

```
At /Users/SherlockHolmes/.atom/packages/p5js-snippets/lib/sourcefetch.js:107

TypeError: Error processing argument at index 0, conversion failure from false
    at TypeError (native)
    at Object.fetch (/packages/p5js-snippets/lib/sourcefetch.js:107:11)
    at /packages/p5js-snippets/lib/sourcefetch.js:30:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  4x -3:50.6.0 sourcefetch:fetch (input.hidden-input)
```

### Non-Core Packages

```
.bin undefined 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.2 
atom-typescript 11.0.3 
atom-wrap-in-tag 0.6.0 
autocomplete-python 1.8.63 
autocomplete-ruby 0.2.7 
browser-plus 0.0.87 
busy-signal 1.4.1 
dracula-theme 2.0.3 
file-icons 2.1.4 
intentions 1.1.2 
jibo-sdk 1.7.1 
language-liquid 0.5.1 
linter 2.1.4 
linter-ruby 1.2.5 
linter-ui-default 1.2.3 
minimap 4.27.1 
p5js-snippets 0.3.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
rails-snippets 2.15.0 
script 3.14.1 
terminal-panel 1.14.1 
terminal-plus 0.14.5 
turbo-javascript 1.4.0 
```

**Comment by bmoren** [comment]
this should be fixed in the most recent release, please make a comment on this issue if it's still a problem!
